language: node_js

node_js:
  - node
  - lts/*
  - 12
  - 10

matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=standard
    - node_js: "lts/*"
      env: TEST_SUITE=coverage

env:
  - TEST_SUITE=unit

script: npm run-script $TEST_SUITE
